dependencies:
  framework: 
    name: pytorch
    version: 1.5.0
  packages:
  - name: dominate
    version: 2.3.5
  - name: numpy
    version: 1.16.2
  - name: opencv-python
    version: 4.1.0.25
  - name: opencv-python-headless
    version: 4.4.0.46
  - name: scipy
    version: 1.2.0
  - name: visdom
    version: 0.1.8.8

classes:
  car,swimming_pool

train:
  script:
    S2OMGAN-Variant/train_platform.py
  inputParams:
    TRAIN_FILE_PATH: SomeGoogleMap15/谷歌影像无标注谷歌地图无标注metadata/15/15_15aligned/
    VAL_FILE_PATH: val # 无实际意义
  outputParams:
    LOG_PATH: monitor
    CHECKPOINT_PATH: latest_net_G_A.pth
# 输出参数必须是文件路径或文件夹路径

evaluate:
  script:
    S2OMGAN-Variant/test_platform.py
  inputParams:
    TEST_FILE_PATH: SomeGoogleMap15/谷歌影像无标注谷歌地图无标注metadata/15/15_15aligned/
    MODEL_FILE: latest_net_G_A.pth
    test_num: 100
  outputParams:
    RESULT_PATH: testResult.json
    OUTPUT_PATH: generated

inference:
  script:
    SMAPGAN/predict.py
  inputParams:
    IMAGE_PATH: shanghai1010_Level17 # 可为图片文件或包含图片文件的文件夹
    MODEL_FILE: latest_net_G_A.pth
  outputParams:
    RESULT_PATH: result.jpg
